#!/usr/bin/env python3

import os

from SCons.Script import ARGUMENTS, Default, Dir, Exit, Glob, SConscript


PLUGIN_BINARY_VERSION = "v1_0"
FFMPEG_LIBRARIES = ["avformat", "avcodec", "swresample", "swscale", "avutil"]

plugin_root = Dir("#").abspath
repository_root = os.path.abspath(os.path.join(plugin_root, "..", ".."))
godot_cpp_dir = os.path.abspath(
    ARGUMENTS.pop("godot_cpp_dir", os.path.join(repository_root, "thirdparty", "godot-cpp"))
)
ffmpeg_root = os.path.abspath(ARGUMENTS.pop("ffmpeg_root", os.environ.get("FFMPEG_ROOT", "")))

if not os.path.isfile(os.path.join(godot_cpp_dir, "SConstruct")):
    print("godot-cpp was not found. Pass godot_cpp_dir=<path>.")
    Exit(1)
if not ffmpeg_root:
    print("FFmpeg SDK was not found. Set FFMPEG_ROOT or pass ffmpeg_root=<path>.")
    Exit(1)

ffmpeg_include = os.path.join(ffmpeg_root, "include")
ffmpeg_lib = os.path.join(ffmpeg_root, "lib")
if not os.path.isfile(os.path.join(ffmpeg_include, "libavformat", "avformat.h")):
    print("Invalid FFmpeg SDK: missing include/libavformat/avformat.h")
    Exit(1)

ARGUMENTS.setdefault("build_profile", os.path.join(plugin_root, "build_profile.json"))
env = SConscript(os.path.join(godot_cpp_dir, "SConstruct"))
if env["platform"] == "windows" and env.get("mingw_prefix"):
    # SCons sanitizes ENV; cc1plus also needs MinGW's DLLs in its search path.
    env.PrependENVPath("PATH", os.path.join(env["mingw_prefix"], "bin"))
env.Append(CPPPATH=[os.path.join(plugin_root, "src"), ffmpeg_include])

if env["platform"] != "ios":
    env.Append(LIBPATH=[ffmpeg_lib])
    if env["platform"] == "windows":
        env.Append(LIBPATH=[os.path.join(ffmpeg_root, "bin")])
    env.Append(LIBS=FFMPEG_LIBRARIES)

if env["platform"] == "android":
    env.Append(LIBS=["m", "dl", "log", "android"])
    env.Append(LINKFLAGS=["-Wl,-z,max-page-size=16384", "-Wl,-z,common-page-size=16384"])
elif env["platform"] == "linux":
    env.Append(LINKFLAGS=["-Wl,-rpath,$$ORIGIN"])
elif env["platform"] == "macos":
    env.Append(LINKFLAGS=["-Wl,-rpath,@loader_path/.."])

if env["platform"] == "windows":
    env.Append(CXXFLAGS=["-std=c++17"] if env.get("use_mingw", False) else ["/std:c++17"])
else:
    env.Append(CXXFLAGS=["-std=c++17"])

sources = Glob(os.path.join(plugin_root, "src", "*.cpp"))
platform_name = env["platform"]
target_name = env["target"]
arch = env["arch"]

if platform_name == "android":
    abi = {"arm64": "arm64-v8a", "x86_64": "x86_64"}.get(arch, arch)
    output = os.path.join(
        plugin_root,
        "bin",
        "android",
        abi,
        "liboriginal_video_{}{}{}".format(PLUGIN_BINARY_VERSION, env["suffix"], env["SHLIBSUFFIX"]),
    )
    library = env.SharedLibrary(output, source=sources)
elif platform_name == "linux":
    output = os.path.join(
        plugin_root,
        "bin",
        "linux",
        arch,
        "liboriginal_video_{}{}{}".format(PLUGIN_BINARY_VERSION, env["suffix"], env["SHLIBSUFFIX"]),
    )
    library = env.SharedLibrary(output, source=sources)
elif platform_name == "macos":
    framework_name = "liboriginal_video_{}.macos.{}".format(PLUGIN_BINARY_VERSION, target_name)
    output = os.path.join(plugin_root, "bin", "macos", framework_name + ".framework", framework_name)
    library = env.SharedLibrary(output, source=sources)
elif platform_name == "ios":
    sdk_name = "simulator" if env["ios_simulator"] else "device"
    output = os.path.join(
        plugin_root,
        "bin",
        "ios",
        "liboriginal_video_{}.ios.{}.{}.a".format(PLUGIN_BINARY_VERSION, target_name, sdk_name),
    )
    library = env.StaticLibrary(output, source=sources)
else:
    output = os.path.join(
        plugin_root,
        "bin",
        "windows",
        arch,
        "original_video_{}{}{}".format(PLUGIN_BINARY_VERSION, env["suffix"], env["SHLIBSUFFIX"]),
    )
    library = env.SharedLibrary(output, source=sources)

env.NoCache(library)
Default(library)
